catcollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('cats/', views.cats_index, name='index'),
    path('cats/<int:cat_id>/', views.cats_detail, name='detail'),
    path('cats/create/', views.CatCreate.as_view(), name='cats_create'),
    path('cats/<int:pk>/update/', views.CatUpdate.as_view(), name='cats_update'),
    path('cats/<int:pk>/delete/', views.CatDelete.as_view(), name='cats_delete'),
]

main_app/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Cat(models.Model):
    name = models.CharField(max_length=100)
    breed = models.CharField(max_length=100)
    description = models.TextField(max_length=250)
    age = models.IntegerField()
    
    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('detail', kwargs={'cat_id': self.id})
    
class Feeding(models.Model): 
    MEALS = (
        ('B', 'Breakfast'),
        ('L', 'Lunch'),
        ('D', 'Dinner'),
    )
    date = models.DateField()
    meal = models.CharField(max_length=1, choices=MEALS, default='B')
    cat = models.ForeignKey(Cat, on_delete=models.CASCADE)
    
    def __str__(self):
        return f"{self.get_meal_display()} on {self.date}"

main_app/views.py
from django.shortcuts import render
from .models import Cat
from django.views.generic.edit import CreateView, UpdateView, DeleteView

# TODO temporary database -> remove this after adding cat model

cats = [
    {'name': 'Lolo', 'breed': 'tabby', 'description': 'furry little demon', 'age': 3},
    {'name': 'Sachi', 'breed': 'calico', 'description': 'gentle and loving', 'age': 2},
]


# Create your views here.
def home(request):
    return render(request, 'home.html') #second argument is the string the represents out template (html file)

def about(request):
    return render(request, 'about.html' )

# def cats_index(request):
#     return render(request, 'cats/index.html', {
#         'cats':cats
#     })

def cats_index(request):
  cats = Cat.objects.all()
  return render(request, 'cats/index.html', { 'cats': cats })

def cats_detail(request, cat_id):
    #we need to communicate with the databse here 
    #return result of redering a template
    cat = Cat.objects.get(id = cat_id)
    return render(request, 'cats/detail.html', {
        'cat':cat
    })
    
    
class CatCreate(CreateView):
    model = Cat
    fields = '__all__'
    # success_url = '/cats/' # not reccomended / not best practice 
    
class CatUpdate(UpdateView):
    model = Cat
    fields = ('description', 'age')

class CatDelete(DeleteView):
    model = Cat
    success_url = '/cats/'

main_app/templates/about.html
{% extends 'base.html'%} {% block content %}
<h1 class="white-text">About the Cat Collector 😻</h1>
<hr />
<p class="white-text">Hire the Cat Collector! 🐈‍⬛</p>
{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Cat Collector</title>
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css"
    />
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
  </head>
  <body>
    <header class="navbar-fixed">
      <nav>
        <div class="nav-wrapper #4dd0e1 cyan lighten-2">
          <ul>
            <li>
              <a href="{% url 'home' %}" class="left brand-logo"
                >&nbsp;&nbsp;Cat Collector 🐱</a
              >
            </li>
          </ul>
          <ul class="right">
            <li><a href="{% url 'about' %}">About</a></li>
            <li><a href="{% url 'cats_create' %}">Add a Cat</a></li>
            <li><a href="{% url 'index' %}">View All My Cats</a></li>
          </ul>
        </div>
      </nav>
    </header>
    <main class="container">{% block content %} {% endblock %}</main>
    <footer class="page-footer #4dd0e1 cyan lighten-2">
      <div class="right">
        All Rights Reserved, &copy; 2024 Cat Collector &nbsp;
      </div>
    </footer>
  </body>
</html>

main_app/templates/cats/detail.html
{% extends 'base.html' %} {% block content %}

<h1>Cat Details</h1>

<div class="row">
  <div class="col s6">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ cat.name }}</span>
        <p>Breed: {{ cat.breed }}</p>
        <p>Description: {{ cat.description|linebreaks }}</p>
        {% if cat.age > 0 %}
        <p>Age: {{ cat.age }}</p>
        {% else %}
        <p>Age: Kitten</p>
        {% endif %}
      </div>
      <div class="card-action">
        <a href="{% url 'cats_update' cat.id %}">Edit</a>
        <a href="{% url 'cats_delete' cat.id %}">Delete</a>
      </div>
    </div>
  </div>
  <!-- New Markup Below -->
  <div class="col s6">
    <table class="striped">
      <thead>
        <tr>
          <th>Date</th>
          <th>Meal</th>
        </tr>
      </thead>
      <tbody>
        {% for feeding in cat.feeding_set.all %}
        <tr>
          <td>{{feeding.date}}</td>
          <td>{{feeding.get_meal_display}}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
  <!-- New Markup Above -->
</div>
{% endblock %}

main_app/templates/cats/index.html
{% extends 'base.html' %} {% block content %}

<h1 class="white-text">Cat List</h1>

{% for cat in cats %}
<a href="/cats/{{ cat.id }}">
  <div class="card">
    <div class="card-content">
      <span class="card-title">{{ cat.name }}</span>
      <p>Breed: {{ cat.breed }}</p>
      <p>Description: {{ cat.description }}</p>
      {% if cat.age > 0 %}
      <p>Age: {{ cat.age }}</p>
      {% else %}
      <p>Age: Kitten</p>
      {% endif %}
    </div>
  </div>
</a>
{% endfor %} {% endblock %}

main_app/templates/home.html
{% extends 'base.html'%} {% block content %}
<h1 class="white-text">Cat Collector 😻</h1>
{% endblock %}

main_app/templates/main_app/cat_confirm_delete.html
{% extends 'base.html' %} {% block content %}
<h1 class="white-text">Are you sure you want to delete {{object.name}}? 😾</h1>
<form action="" method="POST">
  {% csrf_token %}
  <input
    type="submit"
    value="Yes, I want to Delete {{object.name}} 🙀"
    class="btn-large #e53935 red darken-1"
  />
  <a
    class="btn-large #9ccc65 light-green lighten-1"
    href="{% url 'detail' object.id %}"
    >Cancel 😹</a
  >
</form>

{% endblock %}

main_app/templates/main_app/cat_form.html
{% extends 'base.html' %} {% block content %} {% if object %}
<h1 class="white-text">Update {{ object.name }}'s Details</h1>
{% else %}
<h1 class="white-text">Create Cat</h1>
{% endif %}
<div class="row">
  <div class="col s12 m8 offset-m2">
    <div class="card white card-stacked">
      <div class="card-content">
        <span class="card-title white-text">Cat Details</span>
        <form action="" method="POST">
          {% csrf_token %}
          <table class="striped">
            {{ form.as_table }}
          </table>
          <div class="card-action">
            <div class="center-align">
              <button
                type="submit"
                class="btn #ab47bc purple lighten-1 white-text"
              >
                Submit!
              </button>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}